<?php

namespace KeepMe\Repositories;

Use KeepMe\Entities\Children;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildrenRepository extends \Doctrine\ORM\EntityRepository
{
}
