<?php

namespace KeepMe\Repositories;

Use KeepMe\Entities\Nurse;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNurseByUserId($user_id) 
    {
        $dql = 
            " SELECT nurse 
            FROM KeepMe\Entities\Nurse nurse
            WHERE nurse.user = :user_id
        ";

        $query = $this->_em->createQuery($dql);
        $query->setParameter("user_id", $user_id);
        $query->setMaxResults(1);

        return $query->getResult();
    }
}
