<?php

namespace KeepMe\Repositories;

Use KeepMe\Entities\Post;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
}
